kind = "DojoContract"
class_hash = "0x412f1d23d3b13c872ffb8953df0e03a0e01bc0116fc09e067dc6aaeb135f7f1"
original_class_hash = "0x412f1d23d3b13c872ffb8953df0e03a0e01bc0116fc09e067dc6aaeb135f7f1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/stark_farmland_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "stark_farmland::systems::actions::actions"
