kind = "DojoContract"
class_hash = "0x751edff47ea8f802739a8c934b0f4dc826c4f1fdb92fb32a71c0af8040f21c2"
original_class_hash = "0x751edff47ea8f802739a8c934b0f4dc826c4f1fdb92fb32a71c0af8040f21c2"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/stark_farmland_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "stark_farmland::systems::actions::actions"
