[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x7dc571ec1ea63b3a2e85c1e0730707972b198d8932f6f97d2402ef4f2a83be7"
transaction_hash = "0x31573978184a11ae6d08e72afd1be007fabc15ba2a079c19381fdb6b010ffb2"
block_number = 3
seed = "stark_farmland"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x560d608e4d1a4ecb6a8b6f65fc5d070984984b827c9574e246db7e9c6436b5a"
class_hash = "0x46431bc569f5722095940c44d12a0a2c1cfbf84263ec44bee88c98ba49220a4"
original_class_hash = "0x46431bc569f5722095940c44d12a0a2c1cfbf84263ec44bee88c98ba49220a4"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/stark_farmland_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "stark_farmland::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x446b2496d0dd38b7e7cc6772ce363900d5bea276d320595900d29e4bdec6d16"
original_class_hash = "0x446b2496d0dd38b7e7cc6772ce363900d5bea276d320595900d29e4bdec6d16"
abi = "manifests/dev/abis/deployments/models/stark_farmland_models_land_land.json"
name = "stark_farmland::models::land::land"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models.members]]
name = "tree_id"
type = "u128"
key = false

[[models.members]]
name = "is_available"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7327a9dd1b95cbb9e49b23c2d661393f81a17309dc4334ff4d656731d20e0bd"
original_class_hash = "0x7327a9dd1b95cbb9e49b23c2d661393f81a17309dc4334ff4d656731d20e0bd"
abi = "manifests/dev/abis/deployments/models/stark_farmland_models_land_land_manager.json"
name = "stark_farmland::models::land::land_manager"

[[models.members]]
name = "key_name"
type = "felt252"
key = true

[[models.members]]
name = "current_land_id"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5cf4e5598cd2921c70a2a9c4bd810fd8acfea2eeee6be3257bb88fdfca58134"
original_class_hash = "0x5cf4e5598cd2921c70a2a9c4bd810fd8acfea2eeee6be3257bb88fdfca58134"
abi = "manifests/dev/abis/deployments/models/stark_farmland_models_player_player.json"
name = "stark_farmland::models::player::player"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "is_spawn"
type = "bool"
key = false

[[models.members]]
name = "tree_array"
type = "Array<u128>"
key = false

[[models.members]]
name = "land_array"
type = "Array<u128>"
key = false

[[models.members]]
name = "seed_amount"
type = "u128"
key = false

[[models.members]]
name = "fruit_amount"
type = "u128"
key = false

[[models.members]]
name = "last_helped_timestamp"
type = "u64"
key = false

[[models.members]]
name = "last_pranked_timestamp"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x382354d5987dc33471b713c70825e00eca9474fa2a7f1d7e0b38e72cad5b082"
original_class_hash = "0x382354d5987dc33471b713c70825e00eca9474fa2a7f1d7e0b38e72cad5b082"
abi = "manifests/dev/abis/deployments/models/stark_farmland_models_tree_tree.json"
name = "stark_farmland::models::tree::tree"

[[models.members]]
name = "id"
type = "u128"
key = true

[[models.members]]
name = "player"
type = "ContractAddress"
key = false

[[models.members]]
name = "water_value"
type = "u64"
key = false

[[models.members]]
name = "last_watered_timestamp"
type = "u64"
key = false

[[models.members]]
name = "is_fruited"
type = "bool"
key = false

[[models.members]]
name = "is_harvested"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xec0d5753d462a5c90d85ec1be82b3364920af73c5488a6fd594b8b86b6354e"
original_class_hash = "0xec0d5753d462a5c90d85ec1be82b3364920af73c5488a6fd594b8b86b6354e"
abi = "manifests/dev/abis/deployments/models/stark_farmland_models_tree_tree_manager.json"
name = "stark_farmland::models::tree::tree_manager"

[[models.members]]
name = "key_name"
type = "felt252"
key = true

[[models.members]]
name = "current_tree_id"
type = "u128"
key = false
